adidu_shop/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/mine/', show_json_mine, name='show_json_mine'),
    path('xml/<str:product_id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:product_id>/', show_json_by_id, name='show_json_by_id'),
    path('create-product/', create_product, name='create_product'),
    path('product/<str:id>/', show_product, name='show_product'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),\
    path('product/<uuid:id>/edit', edit_product, name='edit_product'),
    path('product/<uuid:id>/delete', delete_product, name='delete_product'),
    path('create-product-ajax', add_product_ajax, name='add_product_ajax'),
    path('update-product-ajax/<uuid:product_id>/', update_product_ajax, name='update_product_ajax'),
    path('delete-product-ajax/<uuid:product_id>/', delete_product_ajax, name='delete_product_ajax'),
    path('login-ajax/', login_ajax, name='login_ajax'),
    path('register-ajax/', register_ajax, name='register_ajax'),
    path('proxy-image/', proxy_image, name='proxy_image'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    CATEGORY_CHOICES = [("sepatu lari", "Running Shoes"),
                        ("sepatu bola", "Football Shoes"),
                        ("jersey bola", "Football Jersey")]

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField()
    thumbnail = models.URLField(blank=True, null=True)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default="sepatu bola")
    is_featured = models.BooleanField(default=False)
    brand = models.CharField(max_length=255)
    stock = models.IntegerField()

    def __str__(self):
        return self.name

main/forms.py
from django.forms import ModelForm
from main.models import Product
from django.utils.html import strip_tags

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description", "thumbnail", "category", "is_featured", "brand", "stock"]

    def clean_name(self):
        name = self.cleaned_data["name"]
        return strip_tags(name)

    def clean_description(self):
        description = self.cleaned_data["description"]
        return strip_tags(description)

    def clean_brand(self):
        brand = self.cleaned_data.get("brand", "")
        return strip_tags(brand)

    def clean_thumbnail(self):
        thumbnail = self.cleaned_data.get("thumbnail", "")
        return strip_tags(thumbnail)

main/views.py
import datetime
import json
import requests
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from main.forms import ProductForm
from main.models import Product
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST, require_http_methods
from django.utils.html import strip_tags

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    filter_type = request.GET.get("filter", "all")
    if filter_type == "all":
        product_list = Product.objects.all()
    else:
        product_list = Product.objects.filter(user=request.user)

    context = {
        'npm' : '2406400524',
        'name': request.user.username,
        'class': 'PBP B',
        'product_list' : product_list,
        'last_login': request.COOKIES.get('last_login', 'Never')
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == 'POST':
        product_entry = form.save(commit = False)
        product_entry.user = request.user
        product_entry.save()
        return redirect('main:show_main')

    context = {'form': form}
    return render(request, "create_product.html", context)

@login_required(login_url='/login')
def show_product(request, id):
    product = get_object_or_404(Product, pk=id)
    context = {
        'product': product
    }

    return render(request, "product_detail.html", context)

def show_xml(request):
    product_list = Product.objects.all()
    xml_data = serializers.serialize("xml", product_list)
    return HttpResponse(xml_data, content_type="application/xml")
    
def show_json(request):
    product_list = Product.objects.all()
    data = [
        {
            'id': product.id,
            'name': product.name,
            'price': product.price,
            'description': product.description,
            'thumbnail': product.thumbnail,
            'category': product.category,
            'category_display': product.get_category_display(),
            'is_featured': product.is_featured,
            'brand': product.brand,
            'stock': product.stock,
            'user_id': product.user_id,
        }
        for product in product_list
    ]

    return JsonResponse(data, safe=False)


@login_required(login_url='/login')
def show_json_mine(request):
    product_list = Product.objects.filter(user=request.user)
    data = [
        {
            'id': product.id,
            'name': product.name,
            'price': product.price,
            'description': product.description,
            'thumbnail': product.thumbnail,
            'category': product.category,
            'category_display': product.get_category_display(),
            'is_featured': product.is_featured,
            'brand': product.brand,
            'stock': product.stock,
            'user_id': product.user_id,
        }
        for product in product_list
    ]

    return JsonResponse(data, safe=False)

def show_xml_by_id(request, product_id):
   try:
       product_item = Product.objects.filter(pk=product_id)
       xml_data = serializers.serialize("xml", product_item)
       return HttpResponse(xml_data, content_type="application/xml")
   except Product.DoesNotExist:
       return HttpResponse(status=404)

def show_json_by_id(request, product_id):
    try:
        product = Product.objects.select_related('user').get(pk=product_id)
        
        data = {
            'id': str(product.id),
            'name': product.name,
            'description': product.description,
            'price': product.price,
            'category': product.category,
            'thumbnail': product.thumbnail,
            'is_featured': product.is_featured,
            'brand': product.brand,
            'stock': product.stock,
            'user_id': product.user_id,
            'user_username': product.user.username if product.user_id else None,
        }
        return JsonResponse(data)
    except Product.DoesNotExist:
        return JsonResponse({'detail': 'Not found'}, status=404)


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
   if request.method == 'POST':
      form = AuthenticationForm(data=request.POST)

      if form.is_valid():
        user = form.get_user()
        login(request, user)
        response = HttpResponseRedirect(reverse("main:show_main"))
        response.set_cookie('last_login', str(datetime.datetime.now()))
        return response

   else:
      form = AuthenticationForm(request)
   context = {'form': form}
   return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    product = get_object_or_404(Product, pk=id)
    form = ProductForm(request.POST or None, instance=product)
    if form.is_valid() and request.method == 'POST':
        form.save()
        return redirect('main:show_main')

    context = {
        'form': form
    }

    return render(request, "edit_product.html", context)

def delete_product(request, id):
    product = get_object_or_404(Product, pk=id)
    product.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
@require_POST
def add_product_ajax(request):
    name = strip_tags(request.POST.get("name"))
    price = request.POST.get("price")
    description = strip_tags(request.POST.get("description"))
    thumbnail = strip_tags(request.POST.get("thumbnail"))
    category = request.POST.get("category")
    brand = strip_tags(request.POST.get("brand"))
    stock = request.POST.get("stock")
    is_featured = request.POST.get("is_featured") == 'on'
    user = request.user if request.user.is_authenticated else None

    new_product = Product(
        user=user,
        name=name,
        price=price,
        description=description,
        thumbnail=thumbnail,
        category=category,
        brand=brand,
        stock=stock,
        is_featured=is_featured,
    )
    new_product.save()

    return HttpResponse(b"CREATED", status=201)

@csrf_exempt
@require_POST
def update_product_ajax(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    product.name = strip_tags(request.POST.get("name"))
    product.price = request.POST.get("price")
    product.description = strip_tags(request.POST.get("description"))
    product.thumbnail = strip_tags(request.POST.get("thumbnail"))
    product.category = request.POST.get("category")
    product.brand = strip_tags(request.POST.get("brand"))
    product.stock = request.POST.get("stock")
    product.is_featured = request.POST.get("is_featured") == 'on'
    product.save()

    return HttpResponse(b"UPDATED", status=200)

@csrf_exempt
@require_http_methods(["DELETE"])
def delete_product_ajax(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    return HttpResponse(b"DELETED", status=200)

@csrf_exempt
@require_POST
def login_ajax(request):
    form = AuthenticationForm(data=request.POST)
    if form.is_valid():
        user = form.get_user()
        login(request, user)
        response = JsonResponse({'redirect': reverse("main:show_main")})
        response.set_cookie('last_login', str(datetime.datetime.now()))
        return response
    return JsonResponse({'errors': form.errors}, status=400)

@csrf_exempt
@require_POST
def register_ajax(request):
    form = UserCreationForm(request.POST)
    if form.is_valid():
        form.save()
        return JsonResponse({'redirect': reverse("main:login")})
    return JsonResponse({'errors': form.errors}, status=400)


@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        name = strip_tags(data.get("name", ""))
        description = strip_tags(data.get("description", ""))
        thumbnail = data.get("thumbnail", "")
        category = data.get("category", "")
        is_featured = data.get("is_featured", False)
        brand = strip_tags(data.get("brand", ""))
        price = data.get("price", 0)
        stock = data.get("stock", 0)
        user = request.user

        new_product = Product(
            user=user,
            name=name,
            description=description,
            thumbnail=thumbnail,
            category=category,
            is_featured=is_featured,
            brand=brand,
            price=price,
            stock=stock,
        )
        new_product.save()

        return JsonResponse({"status": "success"}, status=200)

    return JsonResponse({"status": "error"}, status=401)


def proxy_image(request):
    image_url = request.GET.get('url')
    if not image_url:
        return HttpResponse('No URL provided', status=400)

    try:
        response = requests.get(image_url, timeout=10)
        response.raise_for_status()

        return HttpResponse(
            response.content,
            content_type=response.headers.get('Content-Type', 'image/jpeg')
        )
    except requests.RequestException as e:
        return HttpResponse(f'Error fetching image: {str(e)}', status=500)

main/templates/card_product.html
{% load static %}
{% load humanize %}
<article class="group bg-white rounded-lg border border-stone-300 shadow-sm hover:shadow-lg transition-shadow duration-400 overflow-hidden">
  <!-- Thumbnail -->
  <div class="aspect-[16/9] relative overflow-hidden">
    {% if product.thumbnail %}
      <img src="{{ product.thumbnail }}" alt="{{ product.name }}" class="w-full h-full object-cover transform transition-transform duration-300 group-hover:scale-105">
    {% else %}
      <div class="w-full h-full bg-gray-200"></div>
    {% endif %}

    <!-- Category Badge -->
    <div class="absolute top-3 left-3">
      <span class="inline-flex items-center px-2.5 py-0.5 rounded-md text-xs font-medium bg-gradient-to-r from-emerald-500 to-teal-600 text-white shadow-md">
        {{ product.get_category_display }}
      </span>
    </div>

    <!-- Status Badges -->
    <div class="absolute top-3 right-3 flex space-x-2">
      {% if product.is_featured %}
        <span class="inline-flex items-center px-2 py-1 rounded-md text-xs font-medium bg-yellow-200 text-yellow-700 shadow-md">
          Featured
        </span>
      {% endif %}
    </div>
  </div>

  <!-- Content -->
  <div class="p-5">
    <div class="flex items-center text-sm text-stone-500 mb-3">
        <span class="text-stone-900 font-medium">{{ product.brand }}</span>
        <span class="mx-2">-</span>
        <span class="text-stone-900 font-medium">Rp. {{ product.price|intcomma }}</span>
    </div>

    <h3 class="text-lg font-semibold text-stone-900 mb-3 line-clamp-2 leading-tight">
      <a href="{% url 'main:show_product' product.id %}" class="hover:text-teal-600 transition-colors">
        {{ product.name }}
      </a>
    </h3>

    <p class="text-stone-600 text-sm leading-relaxed line-clamp-3 mb-4">
      {{ product.description|truncatewords:20 }}
    </p>

    <!-- Action Buttons -->
    {% if user.is_authenticated and product.user == user %}
      <div class="flex items-center justify-between pt-4 border-t border-stone-100">
        <a href="{% url 'main:show_product' product.id %}" class="text-teal-600 hover:text-teal-700 font-medium text-sm transition-colors">
          Read more
        </a>
        <div class="flex space-x-2">
          <a href="{% url 'main:edit_product' product.id %}" class="text-stone-600 hover:text-stone-700 text-sm transition-colors">
            Edit
          </a>
          <a href="{% url 'main:delete_product' product.id %}" class="text-red-600 hover:text-red-700 text-sm transition-colors">
            Delete
          </a>
        </div>
      </div>
    {% else %}
      <div class="pt-4 border-t border-stone-100">
        <a href="{% url 'main:show_product' product.id %}" class="text-teal-600 hover:text-teal-700 font-medium text-sm transition-colors">
          Read more →
        </a>
      </div>
    {% endif %}
  </div>
</article>

main/templates/create_product.html
{% extends 'base.html' %}
{% block meta %}
<title>Create Product - Adidu Shop</title>
{% endblock meta %}

{% block content %}
<div class="bg-stone-50 w-full min-h-screen">
  <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    
    <!-- Back Navigation -->
    <div class="mb-6">
      <a href="{% url 'main:show_main' %}" class="text-stone-600 hover:text-stone-900 font-medium transition-colors">
        ← Back to Products
      </a>
    </div>
    
    <!-- Form -->
    <div class="bg-white rounded-lg border border-stone-200 p-6 sm:p-8 form-style">
      <div class="mb-8">
        <h1 class="text-2xl font-bold text-stone-900 mb-2">Create New Product</h1>
        <p class="text-stone-600">Add a new item to your product catalog</p>
      </div>
      
      <form method="POST" class="space-y-6">
        {% csrf_token %}
        {% for field in form %}
          <div>
            <label for="{{ field.id_for_label }}" class="block text-sm font-medium text-stone-700 mb-2">
              {{ field.label }}
            </label>
            <div class="w-full">
              {{ field }}
            </div>
            {% if field.help_text %}
              <p class="mt-1 text-sm text-stone-500">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="mt-1 text-sm text-red-600">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        
        <div class="flex flex-col sm:flex-row gap-4 pt-6 border-t border-stone-200">
          <a href="{% url 'main:show_main' %}" class="order-2 sm:order-1 px-6 py-3 border border-stone-300 text-stone-700 rounded-md font-medium hover:bg-stone-50 transition-colors text-center">
            Cancel
          </a>
          <button type="submit" class="order-1 sm:order-2 flex-1 bg-teal-600 text-white px-6 py-3 rounded-md font-medium hover:bg-teal-700 transition-colors">
            Publish Product
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

main/templates/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>AdiduShop</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="bg-stone-50 w-full pt-16 min-h-screen">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">

    <!-- Header Section -->
    <div class="mb-8">
      <h1 class="text-3xl font-bold text-stone-900 mb-2">Latest Products</h1>
      <p class="text-stone-600">Browse the newest items in our catalog!</p>
    </div>
    
    <button onclick="showModal()" class="inline-flex items-center px-4 py-2 bg-white text-teal-600 font-semibold outline outline-2 outline-teal-600 outline-offset-[-2px] rounded-md hover:bg-teal-600 hover:text-white transition-colors mb-4">
        Create Product
      </button>
      
    <!-- Filter Section -->
    <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-8 bg-white rounded-lg border border-stone-200 p-4">
      <div class="flex space-x-3 mb-4 sm:mb-0">
        <a id="filter-all" href="?" class="{% if request.GET.filter == 'all' or not request.GET.filter  %} bg-teal-600 text-white{% else %}bg-white text-stone-700 border border-stone-300{% endif %} px-4 py-2 rounded-md font-medium transition-colors hover:bg-teal-600 hover:text-white">
          All Products
        </a>
        <a id="filter-my" href="?filter=my" class="{% if request.GET.filter == 'my' %} bg-teal-600 text-white{% else %}bg-white text-stone-700 border border-stone-300{% endif %} px-4 py-2 rounded-md font-medium transition-colors hover:bg-teal-600 hover:text-white">
          My Products
        </a>
      </div>
      {% if user.is_authenticated %}
        <div class="text-sm text-stone-500">
          Last login: {{ last_login }}
        </div>
      {% endif %}
    </div>

    <!-- Loading State -->
    <div id="loading" class="bg-white rounded-lg border border-stone-200 p-12 text-center hidden">
      <svg class="animate-spin h-8 w-8 text-teal-600 inline-block" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z"></path>
      </svg>
      <p class="text-stone-600 mt-3">Loading products...</p>
    </div>

    <!-- Error State -->
    <div id="error" class="hidden"></div>

    <!-- Product Grid -->
    <div id="grid" class="hidden"></div>

    <!-- Empty State -->
    <div id="empty" class="bg-white rounded-lg border border-stone-200 p-12 text-center hidden">
      <div class="w-48 h-48 mx-auto mb-4">
        <img src="{% static 'image/product-not-found.png' %}" alt="No products available" class="w-full h-full object-contain">
      </div>
      <h3 class="text-lg font-medium text-stone-900 mb-2">No products found</h3>
      <p class="text-stone-500 mb-6">Be the first to add a product to the catalog!</p>
      <button
        id="create-product-btn"
        class="inline-flex items-center px-4 py-2 bg-teal-600 text-white rounded-md hover:bg-teal-700 transition-colors"
      >
        Create Product
      </button>
      
    </div>
  </div>
</div>

<script>
// Configuration
const PRODUCT_API_ENDPOINT = "{% url 'main:show_json' %}";
const CURRENT_USER_ID = "{{ user.id|default_if_none:'' }}";

// DOM Elements
const loadingSpinner = document.getElementById('loading');
const errorMessage = document.getElementById('error');
const emptyStateDisplay = document.getElementById('empty');
const productGridContainer = document.getElementById('grid');
const showAllProductsButton = document.getElementById('filter-all'); 
const showMyProductsButton = document.getElementById('filter-my');

// State Variables
let activeFilter = 'all';
let allProductData = [];

// Helpers
function formatRupiah(n) {
  if (n == null) return '';
  return 'Rp ' + Number(n).toLocaleString('id-ID');
}

// Update filter button appearance
function updateFilterButtonsAppearance() {
  if (!showAllProductsButton || !showMyProductsButton) return;
  
  if (activeFilter === 'all') {
    showAllProductsButton.className = 'bg-teal-600 text-white px-4 py-2 rounded-md font-medium transition-colors hover:bg-teal-700';
    showMyProductsButton.className = 'bg-white text-stone-700 border border-stone-300 px-4 py-2 rounded-md font-medium transition-colors hover:bg-teal-600 hover:text-white';
  } else {
    showMyProductsButton.className = 'bg-teal-600 text-white px-4 py-2 rounded-md font-medium transition-colors hover:bg-teal-700';
    showAllProductsButton.className = 'bg-white text-stone-700 border border-stone-300 px-4 py-2 rounded-md font-medium transition-colors hover:bg-teal-600 hover:text-white';
  }
}

// Show/hide page sections
function displayPageSection({ showLoading = false, showError = false, showEmpty = false, showGrid = false }) {
  loadingSpinner.classList.toggle('hidden', !showLoading);
  errorMessage.classList.toggle('hidden', !showError);
  emptyStateDisplay.classList.toggle('hidden', !showEmpty);
  productGridContainer.classList.toggle('hidden', !showGrid);
  
  if (showGrid) {
    productGridContainer.className = 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6';
  }
}

// Create product card element
function buildProductCardElement(product) {
  const articleElement = document.createElement('article');
  articleElement.className = 'bg-white rounded-lg border border-stone-200 hover:shadow-lg transition-shadow duration-300 overflow-hidden flex flex-col h-full';

  const detailLink = `{% url 'main:show_product' '00000000-0000-0000-0000-000000000000' %}`.replace('00000000-0000-0000-0000-000000000000', product.id);
  const editLink = `{% url 'main:edit_product' '00000000-0000-0000-0000-000000000000' %}`.replace('00000000-0000-0000-0000-000000000000', product.id);
  const deleteLink = `{% url 'main:delete_product' '00000000-0000-0000-0000-000000000000' %}`.replace('00000000-0000-0000-0000-000000000000', product.id);

  const categoryLabel = product.category_display || product.category;
  const isFeatured = product.is_featured;
  const hasLowStock = product.stock < 5;

  const thumbnailHtml = product.thumbnail
    ? `<img src='${product.thumbnail}' alt='${product.name}' class='w-full h-full object-cover'>`
    : `<div class='w-full h-full bg-gradient-to-br from-stone-100 to-stone-200 flex items-center justify-center'></div>`;

  const featuredBadge = isFeatured
    ? `<span class='inline-flex items-center px-2 py-1 rounded text-xs font-medium bg-yellow-100 text-yellow-800'>Featured</span>` 
    : '';
  const stockBadge = hasLowStock
    ? `<span class='inline-flex items-center px-2 py-1 rounded text-xs font-medium bg-red-100 text-red-800'>Low Stock</span>`
    : '';

  const editDeleteButtons = CURRENT_USER_ID && Number(CURRENT_USER_ID) === Number(product.user_id)
  ? `<div class='flex space-x-2'>
      <button onclick="showEditModal('${product.id}')" class="text-stone-600 hover:text-stone-700 text-sm transition-colors">Edit</button>
      <button onclick="deleteProductEntry('${product.id}')" class="text-red-600 hover:text-red-700 text-sm transition-colors">Delete</button>
    </div>`
  : '';

  const completeCardHtml = `
    <div class="aspect-[16/9] relative overflow-hidden">
      ${thumbnailHtml}
      <div class="absolute top-3 left-3">
        <span class="inline-flex items-center px-2.5 py-0.5 rounded-md text-xs font-medium bg-teal-600 text-white">${categoryLabel}</span>
      </div>
      <div class="absolute top-3 right-3 flex space-x-2">
        ${featuredBadge}
        ${stockBadge}
      </div>
    </div>
    <div class="p-5 flex flex-col flex-1">
      <h3 class="text-lg font-semibold text-stone-900 mb-3 line-clamp-2 leading-tight">
        <a href="${detailLink}" class="hover:text-teal-600 transition-colors">${product.name}</a>
      </h3>
      <p class="text-stone-600 text-sm leading-relaxed line-clamp-3 mb-4">${product.description}</p>
      <div class="mt-auto pt-4 border-t border-stone-100 flex items-center justify-between">
        <span class="text-teal-700 font-semibold">${formatRupiah(product.price)}</span>
        ${editDeleteButtons}
      </div>
    </div>
  `;

  articleElement.innerHTML = completeCardHtml;
  return articleElement;
}

// Render all product cards
function renderAllProductCards(products) {
  productGridContainer.innerHTML = '';
  products.forEach(product => {
    const cardElement = buildProductCardElement(product);
    productGridContainer.appendChild(cardElement);
  });
}

// Filter and display products
function filterAndDisplayProducts() {
  updateFilterButtonsAppearance();
  
  const filteredProducts = activeFilter === 'all'
    ? allProductData
    : allProductData.filter(product => Number(product.user_id) === Number(CURRENT_USER_ID));
  
  if (filteredProducts.length === 0) {
    displayPageSection({ showEmpty: true });
  } else {
    renderAllProductCards(filteredProducts);
    displayPageSection({ showGrid: true });
  }
}

// Fetch product data from server
async function fetchProductsFromServer() {
  try {
    displayPageSection({ showLoading: true });
    
    const response = await fetch(PRODUCT_API_ENDPOINT, {
      headers: { 'Accept': 'application/json' },
    });

    if (!response.ok) {
      throw new Error('Failed to fetch product data from server');
    }

    const productData = await response.json();
    allProductData = productData || [];
    
    filterAndDisplayProducts();
  } catch (error) {
    console.error('Error loading products:', error);
    displayPageSection({ showError: true });
  }
}

// Event handlers
function handleShowAllProductsClick() {
  activeFilter = 'all';
  filterAndDisplayProducts();
}

function handleShowMyProductsClick() {
  activeFilter = 'my';
  filterAndDisplayProducts();
}

// Initialize page
function initializeProductPage() {
  showAllProductsButton.addEventListener('click', handleShowAllProductsClick);
  showMyProductsButton.addEventListener('click', handleShowMyProductsClick);
  
  fetchProductsFromServer();
}

// Start application
initializeProductPage();

document.addEventListener('productAdded', function() {
    // Refresh data tanpa reload halaman
    fetchProductsFromServer(); // [FIX] sebelumnya salah ketik: fetchProductFromServer()
});

document.getElementById("productForm").addEventListener("submit", function(e) {
    e.preventDefault();
    addProductEntry();
})

document.addEventListener('productUpdated', fetchProductsFromServer);

// [AJAX EDIT] Buka modal edit + prefill form, lalu submit akan memanggil updateProductEntry(productId)
function showEditModal(productId) {
  const item = allProductData.find(p => String(p.id) === String(productId));
  if (!item) return;

  const form = document.getElementById('productForm');
  if (!form) return;

  form.reset();
  form.name.value = item.name || '';
  form.price.value = item.price || '';
  form.description.value = item.description || '';
  form.category.value = item.category || '';
  form.brand.value = item.brand || '';
  form.stock.value = item.stock || '';
  form.thumbnail.value = item.thumbnail || '';
  form.is_featured.checked = !!item.is_featured;

  form.onsubmit = function(e) {
    e.preventDefault();
    updateProductEntry(productId);
  };

  showModal();
}

// [AJAX DELETE] Hapus produk lalu refresh grid via event
async function deleteProductEntry(productId) {
  const ok = confirm("Are you sure you want to delete this product?");
  if (!ok) return;

  await fetch(`/delete-product-ajax/${productId}/`, {
    method: "DELETE",
  });

  showToast('Product deleted successfully!', '', 'success');
  document.dispatchEvent(new CustomEvent('productUpdated'));
}
</script>

{% endblock content %}